### ISSUE TITLE
Make security issues that won't be fixed more visible

### ISSUE THREAD

**Issue by michag86** [nextcloud/security-advisories#11]
for the moment, there are thre security issues that won't be fixed for stable12 and stable13:
https://nextcloud.com/security/advisory/?id=NC-SA-2018-011
https://nextcloud.com/security/advisory/?id=NC-SA-2018-012
https://nextcloud.com/security/advisory/?id=NC-SA-2018-014

It would be helpful, if they are also listed for 12 and 13 releases with notice, that thay won't be fixed. And this should be also part of the security advisory content.

If there are workarounds for supported versions, that won't be fixed, it would be useful to add it to the advisory.

**Comment by michag86** [comment]
cc @MorrisJobke @rullzer

**Comment by LukasReschke** [comment]
We'll consider this in future advisories as we moved to GitHub Security Advisories and this gives us a bit more flexibility. (https://github.com/nextcloud/security-advisories/security/advisories?state=published)
